### ISSUE TITLE
Add a setting for preferred resolution 

### ISSUE THREAD

**Issue by MohamedRadwan** [LagradOst/CloudStream-2#18]
I am not sure if this would be possible with the current scrapper but it would be nice to have the ability to select between different preferred resolutions in the settings.

**Comment by LagradOst** [comment]
You can select a mirror, but it is impossible for me to know beforehand what resolution a mirror has without making an extra request, so I cant add it. Right now the names are just a guess based on the name of the file, so I cant trust that. I order them by speed, quality and reliability based on experience with the provider. I know that it is a frequently asked for feature, but I cant add it due to having 15 or so providers avtive and not 1.
