### ISSUE TITLE
Add support for magnet links like stremio

### ISSUE THREAD

**Issue by bluecheeser** [LagradOst/CloudStream-2#24]
Pls add support for magnet/torrent links like stremio(foss) which streams torrents instead of downloading, u can also add add-on support like stremio eg.torrentio(gets links from rarbg.to,tpb,nyaa.si etc.) which makes the process more streamlined. Adding torrents will give more option and availability and also torrents generally have higher quality.
 
Stremio: https://www.stremio.com/

Torrentio: https://torrentio.strem.fun/configure

Love your work dude, really want this app to grow as this is one of the best apps I have come across.

**Comment by LagradOst** [comment]
I wont add support for magnet/torrent links in this app, because this is not a torrenting app, and get all links from established streaming sites. This wont change and this is a decision I made early on when creating the app. 

You can clone the repo and add them yourself, but I wont add torrent providers even from a pr. sorry
